### ISSUE TITLE
More complete tutorial for Adguard+Wireguard+Knot+DnsCrypt(oDoH)

### ISSUE THREAD

**Issue by kronflux** [trinib/AdGuard-WireGuard-Unbound-DNScrypt#44]
For those us of with a little less networking and linux know-how, would it be possible to get a more complete example of this setup?
Seems there's a few ports that conflict, and I'm not 100% on what passes what to what, or what settings need to be set in AdGuard.
On paper, I like the sounds of Knot better than Unbound, and I like oDoH more than DoH/Cloudflared, but in practice it's a little advanced.

Thanks

**Comment by trinib** [comment]
@kronflux there are in wiki  

[DNScrypt](https://github.com/trinib/AdGuard-WireGuard-Unbound-Cloudflare/wiki/Install-DNScrypt-proxy-(DoH)(oDoH)(Anonymized-DNS))

[Knot](https://github.com/trinib/AdGuard-WireGuard-Unbound-Cloudflare/wiki/Install-Knot-Resolver)

**Comment by trinib** [comment]
@kronflux if you need help with something you can start a [discussion](https://github.com/trinib/AdGuard-WireGuard-Unbound-Cloudflare/discussions/new)

**Comment by trinib** [comment]
you can try also on https://wiki.archlinux.org/title/Dnscrypt-proxy
