### ISSUE TITLE
Website stops loading due to DNS

### ISSUE THREAD

**Issue by abhishekdotone** [trinib/AdGuard-WireGuard-Unbound-DNScrypt#63]
### Operating System

Ubuntu

### Architecture

64-bit

### Platform

Windows, Android

### Project

Aduard Home, Unbound, DNScrypt

### Browser

Brave, Edge

### Issue

Other (explain in description)

### Issue Description

Hi, I am facing an issue where sites stops loading due to DNS issue.

Example - www.1337x.to stops loading and displays an error message "1337x.to’s DNS address could not be found. Diagnosing the problem. DNS_PROBE_POSSIBLE"

![image](https://user-images.githubusercontent.com/115913670/199213377-73db61b0-1bca-4572-a387-6337b89ebbd6.png)

Occurrence - Occasional !

I am using this setup since past 6 months and I started facing this problem from last week.
This happened about 30 mins ago and before that I was able to use the website. I tried flushing Windows DNS cache and Browser's cache but the issue persists.

Browsers tested  - Brave (Windows & Android), Edge.

Using DNScrypt for DoH and here are the logs - [query.log](https://github.com/trinib/AdGuard-WireGuard-Unbound-DNScrypt/files/9909098/query.log)

It seems the browser is querying and getting response but website might have moved to a different IP hence it is not able to load. 

Fix - When using 1.1.1.1 as DNS, website loads just fine.

Do let me know if you require any other info in resolving the issue.

Thank you.

**Comment by trinib** [comment]
@abhishekdotone are you using 1.1.1.1 in adguard home itself or in unbound.conf?

did you  disabe dnscrypt in unbound to see if that's the issue and not unbound?. if so try deleting dnscrypt caches in `/var/cache/dnscrypt-proxy/` folder and try to if it works again

I do not know if you might get anything in service logs<br>create log file:
```
sudo touch /var/log/dnscrypt-proxy/dnscrypt.log
```

to add in "dnscrypt-proxy.toml":
```
## Log level (0-6, default: 2 - 0 is very verbose, 6 only contains fatal errors)

log_level = 2

## Log file for the application, as an alternative to sending logs to
## the standard system logging service (syslog/Windows event log).
##
## This file is different from other log files, and will not be
## automatically rotated by the application.

log_file = '/var/log/dnscrypt-proxy/dnscrypt.log'

## When using a log file, only keep logs from the most recent launch.

log_file_latest = false
```

restart the service
```
sudo systemctl status dnscrypt-proxy.service
```

**Comment by trinib** [comment]
@abhishekdotone did you solve this issue ..

**Comment by abhishekdotone** [comment]
@trinib Apologies for replying so late. Actually I later figured out 1337x was down but Cloudflare mostly cache webpages so it appeared at that moment that it was working using there DNS. Apart from this I had issues with Facebook & Instagram but they usually have config problems at there end so I don't think my setup is at fault. Also from past 10 days, I did not face any issues.

Long story short, you can mark this issue as Solved !

**Comment by trinib** [comment]
@abhishekdotone  thanks for the info ..
