### ISSUE TITLE
DOH not working and not showing on cloudfare website. 

### ISSUE THREAD

**Issue by lutfor-diu** [trinib/AdGuard-WireGuard-Unbound-DNScrypt#64]
### Operating System

DietPi

### Architecture

32-bit

### Platform

Windows, Linux

### Project

Aduard Home, Unbound, DNScrypt

### Browser

Edge

### Issue

Not working

### Issue Description

tried your Dnscrypt config code but cloudfare showing that i'm not using DOH, here i have attached the Dnscrypt config 

```
### More info about dnscrypt-proxy configuration settings
##go to: https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml

### List of local addresses and ports to listen to. Can be IPv4 and/or IPv6.
### Example with both IPv4 and IPv6:
## listen_addresses = ['127.0.0.1:53', '[::1]:53']
## To listen to all IPv4 addresses, use `listen_addresses = ['0.0.0.0:53']`
## To listen to all IPv4+IPv6 addresses, use `listen_addresses = ['[::]:53']`
listen_addresses = ['127.0.0.1:6053', '[::1]:6053']
 
### Use servers reachable over IPv6 -- Do not enable if you don't have IPv6 connectivity
ipv6_servers = true
block_ipv6 = false

### Enable a DNS cache to reduce latency and outgoing traffic(set false if using Unbound)
cache = false

### Use servers implementing the specific protocol
dnscrypt_servers = false
odoh_servers = false
doh_servers = true

### You can choose other servers from public resolver list that is fastest for you
##go to: https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v3/public-resolvers.md
#or for easier readable & searchable server database: https://theummahentrepreneur.notion.site/DNScrypt-DOH-servers-75553dc433194fd1a4e641f4918611ab
##(not all servers support anonymized DNS feature). Using dnscrypt.ca-1 as example that supports it

### For oDoH, REPLACE cloudflare/cloudflare-ipv6 with 'odoh-cloudflare'
### For DoH(dnscrypt) and anonymized dns, REPLACE cloudflare/cloudflare-ipv6 with 'dnscrypt.ca-1'
### For DoH(dnscrypt) and anonymized dns with Cloudflare, only ADD 'dnscrypt.ca-1' to server_names
server_names = ['cloudflare', 'cloudflare-ipv6']
### Example of Quad9 DNS servers with Quad9_DNScrypt anonymized servers:
#server_names = ['quad9-doh-ip4-port5053-filter-ecs-pri', 'quad9-doh-ip6-port5053-filter-ecs-pri', 'quad9-dnscrypt-ip4-filter-pri', 'quad9-dnscrypt-ip6-filter-pri']

### Servers ###
### For more sources and resolver lists: https://github.com/DNSCrypt/dnscrypt-proxy/wiki/DNS-server-sources
[sources]
  [sources.'public-resolvers']
  url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
  cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''

### Anonymized DNS relays ####
  [sources.'relays']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md', 'https://download.dnscrypt.info/resolvers-list/v3/relays.md', 'https://ipv6.download.dnscrypt.info/resolvers-list/v3/relays.md']
  cache_file = '/var/cache/dnscrypt-proxy/relays.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''

### oDoH server and relay is already set here. For more servers and relays 
##go to: https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Oblivious-DoH
### For DoH(dnscrypt) server with anonymized DNS, replace odoh-cloudflare with 'dnscrypt.ca-1'
### For DoH(dnscrypt) relays set to ['*'] for random server(could get a slow 1) 
##or choose a relay server that is fastest for you: https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v3/relays.md
[anonymized_dns]
routes = [
    { server_name='odoh-cloudflare', via=['odohrelay-koki-ams', 'odohrelay-crypto-sx']}
]

### ODoH (Oblivious DoH) servers and relays ###
  [sources.'odoh-servers']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/odoh-servers.md', 'https://download.dnscrypt.info/resolvers-list/v3/odoh-servers.md']
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  cache_file = '/var/cache/dnscrypt-proxy/odoh-servers.md'
  refresh_delay = 72
  prefix = ''
  [sources.'odoh-relays']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/odoh-relays.md', 'https://download.dnscrypt.info/resolvers-list/v3/odoh-relays.md']
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  cache_file = '/var/cache/dnscrypt-proxy/odoh-relays.md'
  refresh_delay = 72
  prefix = ''

[query_log]
  file = '/var/log/dnscrypt-proxy/query.log'

[nx_log]
  file = '/var/log/dnscrypt-proxy/nx.log'
```

**Comment by trinib** [comment]
need logs

**Comment by lutfor-diu** [comment]
> need logs
I have medium knowledge. Please guide me, how to do that?

**Comment by trinib** [comment]
@lutfor-diu 
```
sudo nano /var/log/dnscrypt-proxy/query.log
```

but what does `sudo systemctl status dnscrypt-proxy.service` outputs ?

**Comment by lutfor-diu** [comment]
> @lutfor-diu
> 
> ```
> sudo nano /var/log/dnscrypt-proxy/query.log
> ```
> 
> but what does `sudo systemctl status dnscrypt-proxy.service` outputs ?

Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Now listening to [::1]:6053 [UDP]
Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Now listening to [::1]:6053 [TCP]
Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [odoh-relays] loaded
Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [public-resolvers] loaded
Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [relays] loaded
Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [odoh-servers] loaded
Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Firefox workaround initialized
Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] [cloudflare] OK (DoH) - rtt: 59ms
Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Server with the lowest initial latency: cloudflare (rtt: 59ms)
Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] dnscrypt-proxy is ready - live servers: 1

**Comment by lutfor-diu** [comment]
sudo nano /var/log/dnscrypt-proxy/query.log

empty.

**Comment by trinib** [comment]
> > @lutfor-diu
> > 
> > ```
> > sudo nano /var/log/dnscrypt-proxy/query.log
> > ```
> > 
> > but what does `sudo systemctl status dnscrypt-proxy.service` outputs ?
> ```
> Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Now listening to [::1]:6053 [UDP]
> Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Now listening to [::1]:6053 [TCP]
> Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [odoh-relays] loaded
> Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [public-resolvers] loaded
> Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [relays] loaded
> Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [odoh-servers] loaded
> Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Firefox workaround initialized
> Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] [cloudflare] OK (DoH) - rtt: 59ms
> Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Server with the lowest initial latency: cloudflare (rtt: 59ms)
> Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] dnscrypt-proxy is ready - live servers: 1
> ```

you have odoh server and not cloudflare.. check the configurations again

**Comment by lutfor-diu** [comment]
> > > @lutfor-diu
> > > ```
> > > sudo nano /var/log/dnscrypt-proxy/query.log
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > but what does `sudo systemctl status dnscrypt-proxy.service` outputs ?
> > 
> > 
> > ```
> > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Now listening to [::1]:6053 [UDP]
> > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Now listening to [::1]:6053 [TCP]
> > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [odoh-relays] loaded
> > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [public-resolvers] loaded
> > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [relays] loaded
> > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [odoh-servers] loaded
> > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Firefox workaround initialized
> > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] [cloudflare] OK (DoH) - rtt: 59ms
> > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Server with the lowest initial latency: cloudflare (rtt: 59ms)
> > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] dnscrypt-proxy is ready - live servers: 1
> > ```
> 
> you have odoh source and not doh cloudflare source.. check the configurations again

what will be the config than? can you help please

**Comment by trinib** [comment]
> > > > @lutfor-diu
> > > > ```
> > > > sudo nano /var/log/dnscrypt-proxy/query.log
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > but what does `sudo systemctl status dnscrypt-proxy.service` outputs ?
> > > 
> > > 
> > > ```
> > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Now listening to [::1]:6053 [UDP]
> > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Now listening to [::1]:6053 [TCP]
> > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [odoh-relays] loaded
> > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [public-resolvers] loaded
> > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [relays] loaded
> > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [odoh-servers] loaded
> > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Firefox workaround initialized
> > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] [cloudflare] OK (DoH) - rtt: 59ms
> > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Server with the lowest initial latency: cloudflare (rtt: 59ms)
> > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] dnscrypt-proxy is ready - live servers: 1
> > > ```
> > 
> > 
> > you have odoh source and not doh cloudflare source.. check the configurations again
> 
> what will be the config than? can you help please

server_names = ['cloudflare', 'cloudflare-ipv6']

**Comment by lutfor-diu** [comment]
> > > > > @lutfor-diu
> > > > > ```
> > > > > sudo nano /var/log/dnscrypt-proxy/query.log
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > but what does `sudo systemctl status dnscrypt-proxy.service` outputs ?
> > > > 
> > > > 
> > > > ```
> > > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Now listening to [::1]:6053 [UDP]
> > > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Now listening to [::1]:6053 [TCP]
> > > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [odoh-relays] loaded
> > > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [public-resolvers] loaded
> > > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [relays] loaded
> > > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [odoh-servers] loaded
> > > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Firefox workaround initialized
> > > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] [cloudflare] OK (DoH) - rtt: 59ms
> > > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Server with the lowest initial latency: cloudflare (rtt: 59ms)
> > > > Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] dnscrypt-proxy is ready - live servers: 1
> > > > ```
> > > 
> > > 
> > > you have odoh source and not doh cloudflare source.. check the configurations again
> > 
> > 
> > what will be the config than? can you help please
> 
> server_names = ['cloudflare', 'cloudflare-ipv6']

i used this but same problem.

**Comment by trinib** [comment]
@lutfor-diu  this line indicates odoh source was added `odoh-cloudflare`
```
Nov 02 19:56:43 DietPi dnscrypt-proxy[1082]: [2022-11-02 19:56:43] [NOTICE] Source [odoh-servers] loaded
```

I do not know why is shows that if you say its not added .. I have not in a while tried dietpi 32bit but i doubt the OS is the problem with this type of issue .. try using port 5353 or/and remove cache files in `/var/cache/dnscrypt-proxy/`

**Comment by trinib** [comment]
@lutfor-diu  im wronf it suppose to show sources loaded.. i ll get back to

**Comment by trinib** [comment]
@lutfor-diu  sorry about that i was kind of trying to multitask .. now i took a proper look at the issue i realized that you are using only ipv4 meaning you are not using ::1 or the system ipv6 in DNS option on windows or linux .. Do you have ipv6  `turned off` in windows and linux ??

**Comment by lutfor-diu** [comment]
> @lutfor-diu sorry about that i was kind of trying to multitask .. now i took a proper look at the issue i realized that you are using only ipv4 meaning you are not using ::1 or the system ipv6 in DNS option on windows or linux .. Do you have ipv6 `turned off` in windows and linux ??

My isp doesn't support ipv6, and yes ipv6 disabled in Linux

**Comment by trinib** [comment]
> > @lutfor-diu sorry about that i was kind of trying to multitask .. now i took a proper look at the issue i realized that you are using only ipv4 meaning you are not using ::1 or the system ipv6 in DNS option on windows or linux .. Do you have ipv6 `turned off` in windows and linux ??
> 
> My isp doesn't support ipv6, and yes ipv6 disabled in Linux

ok try on windows

**Comment by trinib** [comment]
@lutfor-diu  you have this off ?
![image](https://user-images.githubusercontent.com/18756975/199602748-5bd77e39-551e-4f77-814b-6267e95b9846.png)

**Comment by lutfor-diu** [comment]
> @lutfor-diu you have this off ? ![image](https://user-images.githubusercontent.com/18756975/199602748-5bd77e39-551e-4f77-814b-6267e95b9846.png)

![Screenshot_1](https://user-images.githubusercontent.com/32225836/199647554-8ac506e9-489b-4947-a00d-83d0dbd5e329.png)

**Comment by lutfor-diu** [comment]
> > > @lutfor-diu sorry about that i was kind of trying to multitask .. now i took a proper look at the issue i realized that you are using only ipv4 meaning you are not using ::1 or the system ipv6 in DNS option on windows or linux .. Do you have ipv6 `turned off` in windows and linux ??
> > 
> > 
> > My isp doesn't support ipv6, and yes ipv6 disabled in Linux
> 
> ok try on windows

not working

**Comment by lutfor-diu** [comment]
> > > @lutfor-diu sorry about that i was kind of trying to multitask .. now i took a proper look at the issue i realized that you are using only ipv4 meaning you are not using ::1 or the system ipv6 in DNS option on windows or linux .. Do you have ipv6 `turned off` in windows and linux ??
> > 
> > 
> > My isp doesn't support ipv6, and yes ipv6 disabled in Linux
> 
> ok try on windows

not working
![Screenshot_2](https://user-images.githubusercontent.com/32225836/199647641-23e17f3f-6584-46d1-9265-1da0f6a9d4d0.png)

**Comment by trinib** [comment]
have you tested dnscrypt by itself to see if its showing DoH? turn off dot, remove 127.0.0.1:53

**Comment by trinib** [comment]
try using port 5353 instead of 6053

**Comment by lutfor-diu** [comment]
> try using port 5353 instead of 6053
brother i tried with the default port 5353, same result, DOT works but DOH not working

**Comment by trinib** [comment]
i do not see any error in the logs . you should be seeing  DoH connected .. check adguard home and see if any configuration was wrong

**Comment by trinib** [comment]
try it on rasberry os to see if its not a issue with dietpi

it is strange it's not showing

**Comment by trinib** [comment]
@lutfor-diu according to logs everything seems fine .. what do you get in query log ?
 [monitor logs](https://github.com/trinib/AdGuard-WireGuard-Unbound-DNScrypt#use-tail-command-to-monitor-logs-in-realtime)

**Comment by lutfor-diu** [comment]
> @lutfor-diu according to logs everything seems fine .. what do you get in query log ? [monitor logs](https://github.com/trinib/AdGuard-WireGuard-Unbound-DNScrypt#use-tail-command-to-monitor-logs-in-realtime)

after several service restart its working now. dont know where i did mistake. thank you for your awesome guide. 
![Screenshot_1](https://user-images.githubusercontent.com/32225836/199876346-508893e7-ce14-4a95-87e3-35487aab1c5b.png)

**Comment by lutfor-diu** [comment]
> @lutfor-diu according to logs everything seems fine .. what do you get in query log ? [monitor logs](https://github.com/trinib/AdGuard-WireGuard-Unbound-DNScrypt#use-tail-command-to-monitor-logs-in-realtime)

how to add more server?

**Comment by trinib** [comment]
https://github.com/trinib/AdGuard-WireGuard-Unbound-DNScrypt/wiki/DNS-Providers

**Comment by lutfor-diu** [comment]
> https://github.com/trinib/AdGuard-WireGuard-Unbound-DNScrypt/wiki/DNS-Providers

didn't find any dnscrypt server. stubby server will work?
server_names = ['cloudflare', 'cloudflare-ipv6'] want to add here

**Comment by trinib** [comment]
```
### You can choose other servers from public resolver list that is fastest for you
##go to: https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v3/public-resolvers.md
#or for easier readable & searchable server database: https://theummahentrepreneur.notion.site/DNScrypt-DOH-servers-75553dc433194fd1a4e641f4918611ab
##(not all servers support anonymized DNS feature). Using dnscrypt.ca-1 as example that supports it
```

**Comment by lutfor-diu** [comment]
> ```
> ### You can choose other servers from public resolver list that is fastest for you
> ##go to: https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v3/public-resolvers.md
> #or for easier readable & searchable server database: https://theummahentrepreneur.notion.site/DNScrypt-DOH-servers-75553dc433194fd1a4e641f4918611ab
> ##(not all servers support anonymized DNS feature). Using dnscrypt.ca-1 as example that supports it
> ```

added this server `server_names = ['cloudflare', 'cloudflare-ipv6', 'adguard-dns-unfiltered-doh', 'bortzmeyer', 'ams-doh-nl']`

but showing only 1 server running.
`Nov 04 09:43:26 DietPi dnscrypt-proxy[3979]: [2022-11-04 09:43:26] [NOTICE] Now listening to [::1]:5353 [UDP]
Nov 04 09:43:26 DietPi dnscrypt-proxy[3979]: [2022-11-04 09:43:26] [NOTICE] Now listening to [::1]:5353 [TCP]
Nov 04 09:43:26 DietPi dnscrypt-proxy[3979]: [2022-11-04 09:43:26] [NOTICE] Source [public-resolvers] loaded
Nov 04 09:43:26 DietPi dnscrypt-proxy[3979]: [2022-11-04 09:43:26] [NOTICE] Source [relays] loaded
Nov 04 09:43:26 DietPi dnscrypt-proxy[3979]: [2022-11-04 09:43:26] [NOTICE] Source [odoh-servers] loaded
Nov 04 09:43:26 DietPi dnscrypt-proxy[3979]: [2022-11-04 09:43:26] [NOTICE] Source [odoh-relays] loaded
Nov 04 09:43:26 DietPi dnscrypt-proxy[3979]: [2022-11-04 09:43:26] [NOTICE] Firefox workaround initialized
Nov 04 09:43:26 DietPi dnscrypt-proxy[3979]: [2022-11-04 09:43:26] [NOTICE] [cloudflare] OK (DoH) - rtt: 55ms
Nov 04 09:43:26 DietPi dnscrypt-proxy[3979]: [2022-11-04 09:43:26] [NOTICE] Server with the lowest initial latency: cloudflare (rtt: 55ms)
Nov 04 09:43:26 DietPi dnscrypt-proxy[3979]: [2022-11-04 09:43:26] [NOTICE] dnscrypt-proxy is ready - live servers: 1
`

**Comment by trinib** [comment]
working
![image](https://user-images.githubusercontent.com/18756975/199882082-62abc884-341d-4f26-800b-740c2c50b7c9.png)

**Comment by lutfor-diu** [comment]
> working ![image](https://user-images.githubusercontent.com/18756975/199882082-62abc884-341d-4f26-800b-740c2c50b7c9.png)

which code you changed?

**Comment by trinib** [comment]
I just add servers and restart dnscrypt proxy service

**Comment by lutfor-diu** [comment]
> I just add servers and restart dnscrypt proxy service

Hi Brother when input in adguard upstream ip it works but when leave the unbound ip in upstream it didn't work. though unbound forwaded to dnscrypt ipand port. 

doest dnscrypt work with unbound? i did run cloudflare test. not showing DOH but DOT working.

**Comment by trinib** [comment]
> > I just add servers and restart dnscrypt proxy service
> 
> Hi Brother when input in adguard upstream ip it works but when leave the unbound ip in upstream it didn't work. though unbound forwaded to dnscrypt ipand port. 
> 
> doest dnscrypt work with unbound? i did run cloudflare test. not showing DOH but DOT working.

try and  test addresses one by one to see what it getting the error from in adguard
