### ISSUE TITLE
Updating block lists

### ISSUE THREAD

**Issue by Jonesyj83** [trinib/AdGuard-WireGuard-Unbound-DNScrypt#69]
### Operating System

Raspberry Pi

### Architecture

64-bit

### Platform

Linux

### Project

Aduard Home

### Browser

Other

### Issue

Other (explain in description)

### Issue Description

I added all the url's with the python script, do these block lists get updated with new urls automatic or if there is a script that can be run to keep all block lists up to date. I remember with pihole I used to run a script to update all block lists.

**Comment by trinib** [comment]
@Jonesyj83 you can manually update it from within adguard home interface (check for updates button) in blocklist section. I think it updates when Pi restarted. To have a script to create a cron job,  i will have to find the code to see what triggers "check for updates". Or you can ask in Adguard home repo devs.
